约束
1、主键约束
id INT PRIMARY KEY
PRIMARY KEY(id)
PRIMARY KEY(id,NAME)

ALTER TABLE tablename
ADD PRIMARY KEY(colname)

ALTER TABLE tablename
ADD CONSTRAINT pk_1 PRIMARY KEY(colname)

ALTER TABLE tablename
DROP PRIMARY KEY
2、唯一性
phone INT UNIQUE
ALTER TABLE stu
MODIFY colname TYPE(len) uniqeu
3、默认值
phone INT DEFAULT 0
INSERT INTO tablename VALUES(DEFAULT)
4、非空
NAME VARCHAR(20) NOT NULL
5、自动增长
id INT AUTO_INCREMENT
ALTER TABLE stu
MODIFY id INT AUTO_INCREMENT
6、外键
多表之间的关系

