package com.woniu.mapper;

import com.woniu.model.UserinforoleExample;
import com.woniu.model.UserinforoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserinforoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    int countByExample(UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    int deleteByExample(UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    int deleteByPrimaryKey(UserinforoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    int insert(UserinforoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    int insertSelective(UserinforoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    List<UserinforoleKey> selectByExample(UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserinforoleKey record, @Param("example") UserinforoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinforole
     *
     * @mbggenerated Mon Jul 08 10:17:45 CST 2019
     */
    int updateByExample(@Param("record") UserinforoleKey record, @Param("example") UserinforoleExample example);
}