package com.woniu.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.woniu.model.Userinfo;
import com.woniu.model.UserinfoExample;

public interface UserinfoMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int countByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int deleteByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int deleteByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int insert(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int insertSelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	List<Userinfo> selectByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	Userinfo selectByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int updateByExample(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int updateByPrimaryKeySelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbggenerated  Tue Jul 09 09:48:40 CST 2019
	 */
	int updateByPrimaryKey(Userinfo record);

	Userinfo login(Userinfo info);
}