package com.woniu.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stid
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    private Integer stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stname
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    private String stname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.score
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stid
     *
     * @return the value of student.stid
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public Integer getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stid
     *
     * @param stid the value for student.stid
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public void setStid(Integer stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stname
     *
     * @return the value of student.stname
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public String getStname() {
        return stname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stname
     *
     * @param stname the value for student.stname
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public void setStname(String stname) {
        this.stname = stname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.score
     *
     * @return the value of student.score
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.score
     *
     * @param score the value for student.score
     *
     * @mbggenerated Thu Jul 11 11:00:25 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}