package com.woniuxy.domain;
// Generated 2019-6-21 15:07:10 by Hibernate Tools 5.4.2.Final

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer eid;
	private Dept dept;
	private String ename;

	public Emp() {
	}

	public Emp(Dept dept, String ename) {
		this.dept = dept;
		this.ename = ename;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

}
