package com.woniu.model;

import java.math.BigDecimal;

public class Goods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.id
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.typeid
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private Integer typeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goodsName
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private String goodsname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goodsUnitPrice
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private BigDecimal goodsunitprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.rest
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private Integer rest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goodsPhoto
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private String goodsphoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.status
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.description
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.id
	 * @return  the value of goods.id
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.id
	 * @param id  the value for goods.id
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.typeid
	 * @return  the value of goods.typeid
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.typeid
	 * @param typeid  the value for goods.typeid
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goodsName
	 * @return  the value of goods.goodsName
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public String getGoodsname() {
		return goodsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goodsName
	 * @param goodsname  the value for goods.goodsName
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goodsUnitPrice
	 * @return  the value of goods.goodsUnitPrice
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public BigDecimal getGoodsunitprice() {
		return goodsunitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goodsUnitPrice
	 * @param goodsunitprice  the value for goods.goodsUnitPrice
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setGoodsunitprice(BigDecimal goodsunitprice) {
		this.goodsunitprice = goodsunitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.rest
	 * @return  the value of goods.rest
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public Integer getRest() {
		return rest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.rest
	 * @param rest  the value for goods.rest
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setRest(Integer rest) {
		this.rest = rest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goodsPhoto
	 * @return  the value of goods.goodsPhoto
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public String getGoodsphoto() {
		return goodsphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goodsPhoto
	 * @param goodsphoto  the value for goods.goodsPhoto
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setGoodsphoto(String goodsphoto) {
		this.goodsphoto = goodsphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.status
	 * @return  the value of goods.status
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.status
	 * @param status  the value for goods.status
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.description
	 * @return  the value of goods.description
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.description
	 * @param description  the value for goods.description
	 * @mbg.generated  Thu Jul 25 21:09:11 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}