server:
  port: 9100
spring:
#  profiles: eureka2
  security:
    user:
      password: 25802580
      name: admin
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:25802580@localhost:9000/eureka
  instance:
    prefer-ip-address: false
#    hostname: eureka