INSERT INTO `练习` VALUES (5, '张飞', '男', 40, '东大街');
INSERT INTO `练习` VALUES (7, '马云', '男', 40, '西大街');
INSERT INTO `练习` VALUES (8, '马波', '男', 22, '西大街');
INSERT INTO `练习` VALUES (9, '张柏芝', '女', 40, '东大街');
INSERT INTO `练习` VALUES (10, '张韶涵', '女', 40, '东大街');
INSERT INTO `练习` VALUES (11, '张三丰', '男', 40, '南大街');
INSERT INTO `练习` VALUES (12, '张惠妹', '女', 40, '北大街');
INSERT INTO `练习` VALUES (1, '变形金刚', '变形金刚', '张艺谋', 100.00, 1);
INSERT INTO `练习` VALUES (2, '听风者', '梁朝伟', '冯小刚', 110.00, 8);
INSERT INTO `练习` VALUES (3, '三国演绎', '甄子丹', '李安', 200.00, 7);
INSERT INTO `练习` VALUES (4, '龙门飞甲', '李连杰', '张艺谋', 150.00, 4);
INSERT INTO `练习` VALUES (5, '关云长', '李小龙', '张艺谋', 170.00, 2);
INSERT INTO `练习` VALUES (7, '后会无期', '张国立', '冯小刚', 130.00, 2);
INSERT INTO `练习` VALUES (8, '心花路放', '张国荣', '张艺谋', 125.00, 2);
INSERT INTO `练习` VALUES (9, '鹿鼎记', '刘青云', '张艺谋', 105.00, 2);
INSERT INTO `练习` VALUES (12, '木偶奇遇记', '李嘉诚', '冯小刚', 100.00, 3);
INSERT INTO `练习` VALUES (13, '贵妃醉酒', '李玉刚', '李安', 200.00, 8);
INSERT INTO `练习` VALUES (3, '张学良', '男', 66, '北大街');
INSERT INTO `练习` VALUES (12, '张惠妹', '女', 40, '北大街');
INSERT INTO `练习` VALUES (7, '后会无期');
INSERT INTO `练习` VALUES (8, '心花路放');
INSERT INTO `练习` VALUES (9, '鹿鼎记');
INSERT INTO `练习` VALUES (11, '速度与激情8');
INSERT INTO `练习` VALUES (1, '刘欢欢', '男', 60, '北大街');
INSERT INTO `练习` VALUES (3, '张学良', '男', 66, '北大街');
INSERT INTO `练习` VALUES (4, '张曼玉', '女', 52, '西大街');
INSERT INTO `练习` VALUES (5, '张飞', '男', 40, '东大街');
INSERT INTO `练习` VALUES (6, '李嘉诚', '男', 70, '南大街');
INSERT INTO `练习` VALUES (1, '刘欢欢', '男', 60, '北大街');
INSERT INTO `练习` VALUES (2, '张学友', '男', 58, '东大街');
INSERT INTO `练习` VALUES (3, '张学良', '男', 66, '北大街');
INSERT INTO `练习` VALUES (4, '张曼玉', '女', 52, '西大街');
INSERT INTO `练习` VALUES (5, '张飞', '男', 40, '东大街');
INSERT INTO `练习` VALUES (7, '马云', '男', 40, '西大街');
INSERT INTO `练习` VALUES (8, '马波', '男', 22, '西大街');
INSERT INTO `练习` VALUES (9, '张柏芝', '女', 40, '东大街');
INSERT INTO `练习` VALUES (10, '张韶涵', '女', 40, '东大街');
INSERT INTO `练习` VALUES (11, '张三丰', '男', 40, '南大街');
INSERT INTO `练习` VALUES (12, '张惠妹', '女', 40, '北大街');
INSERT INTO `练习` VALUES (1, '刘欢欢', '男', 60, '北大街');
INSERT INTO `练习` VALUES ('马云');
INSERT INTO `练习` VALUES ('张柏芝');
INSERT INTO `练习` VALUES ('张韶涵');
INSERT INTO `练习` VALUES ('张三丰');
INSERT INTO `练习` VALUES ('张惠妹');
INSERT INTO `练习` VALUES ('喜剧');
INSERT INTO `练习` VALUES ('科幻');
INSERT INTO `练习` VALUES ('动漫');
INSERT INTO `练习` VALUES (6);
INSERT INTO `练习` VALUES (10, '倚天屠龙记', '刘嘉玲', '冯小刚', 300.00, 1);
INSERT INTO `练习` VALUES (11, '速度与激情8', '李伟', '张艺谋', 800.00, 2);
INSERT INTO `练习` VALUES (1, '刘欢欢', '男', 60, '北大街');
INSERT INTO `练习` VALUES (2, '张学友', '男', 58, '东大街');
INSERT INTO `练习` VALUES (3, '张学良', '男', 66, '北大街');
INSERT INTO `练习` VALUES (4, '张曼玉', '女', 52, '西大街');
INSERT INTO `练习` VALUES (6, '李嘉诚', '男', 70, '南大街');
INSERT INTO `练习` VALUES (7, '马云', '男', 40, '西大街');
INSERT INTO `练习` VALUES (2, '张学友', '男', 58, '东大街');
INSERT INTO `练习` VALUES (1, '刘欢欢', '男', 60, '北大街');
INSERT INTO `练习` VALUES (3, '张学良', '男', 66, '北大街');
INSERT INTO `练习` VALUES (6, '李嘉诚', '男', 70, '南大街');
INSERT INTO `练习` VALUES (4, '张曼玉', '女', 52, '西大街');
INSERT INTO `练习` VALUES (7, '马云', '男', 40, '西大街');
INSERT INTO `练习` VALUES (0.6667);
INSERT INTO `练习` VALUES (0.3333);
INSERT INTO `练习` VALUES (0.3333, 0.6667);
INSERT INTO `练习` VALUES ('东大街', 4);
INSERT INTO `练习` VALUES ('北大街', 3);
INSERT INTO `练习` VALUES ('南大街', 2);
INSERT INTO `练习` VALUES ('西大街', 3);
INSERT INTO `练习` VALUES ('东大街', 44.5000);
INSERT INTO `练习` VALUES ('北大街', 55.3333);
INSERT INTO `练习` VALUES ('南大街', 55.0000);
INSERT INTO `练习` VALUES ('西大街', 38.0000);
INSERT INTO `练习` VALUES (1, 5);
INSERT INTO `练习` VALUES (2, 3);
INSERT INTO `练习` VALUES (3, 4);
INSERT INTO `练习` VALUES (5, 1);
INSERT INTO `练习` VALUES (7, 1);
INSERT INTO `练习` VALUES (1, 1, 2);
INSERT INTO `练习` VALUES (1, 3, 2);
INSERT INTO `练习` VALUES (2, 2, 5);
INSERT INTO `练习` VALUES (2, 3, 2);
INSERT INTO `练习` VALUES (3, 1, 2);
INSERT INTO `练习` VALUES (4, 1, 2);
INSERT INTO `练习` VALUES (5, 1, 2);
INSERT INTO `练习` VALUES (3, 3, 2);
INSERT INTO `练习` VALUES (4, 3, 2);
INSERT INTO `练习` VALUES (5, 2, 5);
INSERT INTO `练习` VALUES (6, 7, 1);
INSERT INTO `练习` VALUES (6, 1, 2);
INSERT INTO `练习` VALUES (8, 2, 5);
INSERT INTO `练习` VALUES (1, 1, 2);
INSERT INTO `练习` VALUES (1, 3, 2);
INSERT INTO `练习` VALUES (1, 5, 0);
INSERT INTO `练习` VALUES (2, 2, 5);
INSERT INTO `练习` VALUES (2, 3, 2);
INSERT INTO `练习` VALUES (3, 1, 2);
INSERT INTO `练习` VALUES (4, 1, 2);
INSERT INTO `练习` VALUES (5, 1, 2);
INSERT INTO `练习` VALUES (3, 3, 2);
INSERT INTO `练习` VALUES (4, 3, 2);
INSERT INTO `练习` VALUES (5, 2, 5);
INSERT INTO `练习` VALUES (6, 7, 1);
INSERT INTO `练习` VALUES (6, 1, 2);
INSERT INTO `练习` VALUES (8, 2, 5);
